In [18]:
import numpy as np
print(np.ones(10))
print(np.full((2,4),5))# np.full 构造一个大小为 shape 的用指定值填满的数组,

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[5 5 5 5]
 [5 5 5 5]]


In [35]:
a=np.empty((4,2))# np.empty 构造一个大小为 shape 的未初始化数组
print(a)
print(a.itemsize)#每个元素占内存大小
print(a.size)

[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 7.13430793e-321]
 [2.18565566e-312 8.70018274e-313]]
8
8


In [36]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [40]:
#add用法
a=np.arange(9).reshape((3,3))
b=np.arange(3)
print(a)
print(b)
print(np.add(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [51]:
a=np.full((1,10),0)
a[0,1]=2
print(a)


[[0 2 0 0 0 0 0 0 0 0]]


In [88]:
a=np.array([[1,1],[2,2]])
print(a)
print(a.mean())
print(a.mean(axis=1))
print(a.mean(axis=0))

[[1 1]
 [2 2]]
1.5
[1. 2.]
[1.5 1.5]


In [96]:
#average可以计算加权
a=np.array([[1,1],[2,2]])
print(np.average(a))
print(np.average(a,axis=0,weights=[3,1]))
print(np.average(np.arange(1,11),weights=np.arange(10,0,-1)))

1.5
[1.25 1.25]
4.0


In [53]:
print(np.arange(10))
print(np.arange(10)[::1])
print(np.arange(10)[1::1])#从第二个元素开始到最后一个
print(np.arange(10)[2::-1])#从第三个元素开始倒序输出
print(np.arange(10)[5::-2])#从第6个元素开始间隔一个倒序输出
print(np.arange(10)[::-1])#倒序输出
print('\n\n')
a=np.arange(8)
print(a)
print(a[:2])
print(a[0::2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[2 1 0]
[5 3 1]
[9 8 7 6 5 4 3 2 1 0]



[0 1 2 3 4 5 6 7]
[0 1]
[0 2 4 6]


In [58]:
print(np.nonzero([1,2,4,5,0,2]))#找出非0元素的下标

(array([0, 1, 2, 3, 5], dtype=int64),)


In [69]:
# identity 只能创建方阵，eye要灵活一些，可以创建NxM的矩阵，也可以控制对角线的位置
print(np.identity(2))
print(np.eye(3))
print(np.eye(3,4,1))

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [102]:
a=np.ones((5,5))*5
print(a)
a[1:-1,1:-1]=1
a[2,2]=0
print(a)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
[[5. 5. 5. 5. 5.]
 [5. 1. 1. 1. 5.]
 [5. 1. 0. 1. 5.]
 [5. 1. 1. 1. 5.]
 [5. 5. 5. 5. 5.]]


In [2]:
#填充数组
a=np.array([[1,1],[2,2]])
b=np.pad(a,((1,1),(2,2)),'constant',constant_values=(0,3))
#((1,1),(2,2))表示在二维数组array第一维（此处便是行）前面填充1行，最后面填充1行；
               #  在二维数组array第二维（此处便是列）前面填充2列，最后面填充2列
print(a)
print(b)

[[1 1]
 [2 2]]
[[0 0 0 0 3 3]
 [0 0 1 1 3 3]
 [0 0 2 2 3 3]
 [0 0 3 3 3 3]]


In [6]:
a=np.array([1,1])
print(np.pad(a,(1,2),'constant'))

[0 1 1 0 0]


In [29]:
print(np.diag([1,2,3,4]))
print(np.diag([1,2,3,4],1))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [56]:
a=np.zeros((8,8))
a[::2,1::2]=1
a[1::2,::2]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [60]:
a=np.array([[1,1],[0,0]])
print(np.tile(a,(2,3)))#tile用于加倍

[[1 1 1 1 1 1]
 [0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [0 0 0 0 0 0]]


In [75]:
a=np.random.randint(0,9,(5,3))#大于等于0小于9
b=np.random.randint(0,9,(3,5))
print(a.dot(b))
print(a@b)

[[47 52  5 53  9]
 [71 74  9 70 24]
 [65 70 23 71 51]
 [81 85 25 83 59]
 [60 61 10 56 28]]
[[47 52  5 53  9]
 [71 74  9 70 24]
 [65 70 23 71 51]
 [81 85 25 83 59]
 [60 61 10 56 28]]


In [78]:
a=np.arange(1,20)
a[(a>3)&(a<8)]*=-1#将这些书变为相反数
print(a)

[ 1  2  3 -1 -1 -1 -1  8  9 10 11 12 13 14 15 16 17 18 19]


In [98]:
a=np.arange(6).reshape(2,3)
print(a,'\n')
print(np.sum(a,0))
print(np.sum(a,-2))
print(np.sum(a,1))
print(np.sum(a,-1))


[[0 1 2]
 [3 4 5]] 

[3 5 7]
[3 5 7]
[ 3 12]
[ 3 12]


In [115]:
print(np.random.choice(10,3))#0-9选3个

[9 7 4]


In [127]:
a=np.random.uniform(-10,10,10)#左闭右开区间取浮点数
print(a)
print(np.abs(a))#绝对值
print(np.ceil(a))#向上取整
print(np.floor(a))#向下取整


[-4.66243929 -1.09742786  0.18996668  5.25989352 -9.36641126  9.88360621
  3.94627788  3.15083063 -6.02743312 -8.20708658]
[4.66243929 1.09742786 0.18996668 5.25989352 9.36641126 9.88360621
 3.94627788 3.15083063 6.02743312 8.20708658]
[-4. -1.  1.  6. -9. 10.  4.  4. -6. -8.]
[ -5.  -2.   0.   5. -10.   9.   3.   3.  -7.  -9.]


In [136]:
#查找数组的交集、并集、差、对称差,同时排序
a=np.array([1,2,3,5])
b=np.array([2,4,6,2,1])
print(np.intersect1d(a,b))
print(np.union1d(a,b))
print(np.setdiff1d(a,b))#a中有b中没有
print(np.setxor1d(a,b))

[1 2]
[1 2 3 4 5 6]
[3 5]
[3 4 5 6]
