In [92]:
import numpy as np
import random
a=np.random.rand(2,3)
b=np.random.random([2,3])
print(a)
print(b)
np.random.shuffle(b)#上下打乱
print(b)
print(a.max(axis=1))

[[0.13344678 0.57756632 0.28118735]
 [0.8290783  0.21636232 0.86176669]]
[[0.33868632 0.6114279  0.68115954]
 [0.71210534 0.18355099 0.57866566]]
[[0.71210534 0.18355099 0.57866566]
 [0.33868632 0.6114279  0.68115954]]
[0.57756632 0.86176669]


In [102]:
A=np.arange(2,11).reshape([3,3])
b=A.flatten()#函数
print(b)
for i in A.flat:#迭代器
    print(i)



[ 2  3  4  5  6  7  8  9 10]
2
3
4
5
6
7
8
9
10


In [73]:
#合并
a=np.array([1,1,1])
b=np.array([2,2,2])
c=np.vstack((a,b))#vertical竖直的
d=np.hstack((a,b))#horizontal水平的
print(c)
print(c.shape)
print(d)
print(d.shape)

[[1 1 1]
 [2 2 2]]
(2, 3)
[1 1 1 2 2 2]
(6,)


In [107]:
a=np.array([1,1,1])
b=a[:,np.newaxis]#添加新的维度
c=a[np.newaxis,:]
print(b)
print(b.shape)
print(c)
print(c.shape)

[[1]
 [1]
 [1]]
(3, 1)
[[1 1 1]]
(1, 3)


In [76]:
a=np.array([1,1,1])[:,np.newaxis,]#添加列
b=np.array([2,2,2])[:,np.newaxis,]
c=np.vstack((a,b))
d=np.hstack((a,b))
print(c)
print(c.shape)
print(d)
print(d.shape)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
(6, 1)
[[1 2]
 [1 2]
 [1 2]]
(3, 2)


In [5]:
a=np.array([1,1,1])[:,np.newaxis,]#添加列
b=np.array([2,2,2])[:,np.newaxis,]
print(a)
print(b)
print('\n')

c=np.concatenate((a,a,b),axis=1)#h横着加
d=np.concatenate((a,b),axis=0)#竖着加
print(c)
print(d)

[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]


[[1 1 2]
 [1 1 2]
 [1 1 2]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]


In [6]:
#分割数组
a=np.arange(12).reshape([3,4])
print(a)
b=np.split(a,3)#按行分
print(b)
print(b[1])
print('\n\n')
print(np.vsplit(a,3))#竖直
print(np.hsplit(a,2))#水平

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[[4 5 6 7]]



[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [124]:
#值传递
a=np.arange(4)
b=a
c=a.copy()
print(a)
a[0]=11
print(a)
print(b)
print(c)

[0 1 2 3]
[11  1  2  3]
[11  1  2  3]
[0 1 2 3]
